Compatibility with pg14 (#43)

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -23,13 +23,14 @@ jobs:
         - '11'
         - '12'
         - '13'
+        - '14'
 
     steps:
     - uses: actions/checkout@v1
     - name: Set up packages
       run: |
         set -e
-        sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
+        sudo sh -c "echo \"deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main $PG\" > /etc/apt/sources.list.d/pgdg.list"
         sudo apt-get update
         sudo apt-get install -yq --no-install-suggests --no-install-recommends curl postgresql-common lcov libevent-dev pv brotli libbrotli1 libbrotli-dev
         # forbid creation of a main cluster when package is installed
@@ -50,7 +51,7 @@ jobs:
     - name: Run tests
       run: |
         PATH=/usr/lib/postgresql/$PG/bin:$PATH bash -x test.sh
-        if grep -E '(ERROR|FATAL)' test_cluster?/pg_log/postgresql.log | grep -Ev '(no COPY in progress|could not connect to|could not send|database system is shutting|error reading result of streaming command|database system is starting up|log:noisia)'; then exit 1; fi
+        if grep -E '(ERROR|FATAL)' test_cluster?/pg_log/postgresql.log | grep -Ev '(no COPY in progress|could not connect to|could not send|the database system is not yet accepting connections|database system is shutting|error reading result of streaming command|database system is starting up|log:noisia)'; then exit 1; fi
 
     - name: Generate lcov.info
       run: |
